AS = riscv64-unknown-elf-as
CC = riscv64-unknown-elf-gcc
LD = riscv64-unknown-elf-ld
OBJCOPY = riscv64-unknown-elf-objcopy
OBJDUMP = riscv64-unknown-elf-objdump
SIZE = riscv64-unknown-elf-size

ASFLAGS = \
	-mabi=ilp32 \
	-march=rv32imac \

CFLAGS = \
	-mabi=ilp32 \
	-march=rv32imac \

LDSCRIPT = arch/riscv/link.lds

export AS CC LD OBJCOPY OBJDUMP SIZE ASFLAGS CFLAGS LDSCRIPT
