AS = arm-none-eabi-as
CC = arm-none-eabi-gcc
LD = arm-none-eabi-ld
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size

LDSCRIPT = arch/arm/cortex_m/link.lds

export AS CC LD OBJCOPY OBJDUMP SIZE LDSCRIPT
