ASMS = $(wildcard *.s)
SRCS = $(wildcard *.c)
INCLUDES = \
	-I../../ext/arm/cmsis/include \
	-I../../ext/nordic/include \
	-I../../arch/arm/cortex_m \
	-I../../soc/nrf5 \
	-I../../ \

include ../../makefile.inc
